
# update frequency of the kinematics node and socketcan node [Hz]
control_rate: 100

# how often to request status updates from the motors, request rate = control_rate / divider
request_status_divider: 10

# how often to send a heartbeat to the motors, heartbeat rate = control_rate / divider
heartbeat_divider: 5

# number of drive modules (need at least 2)
num_wheels: 4

# radius of the wheels [m]
#   (round wheels = 88mm, flat wheels = 90mm)
wheel_radius: 0.088

# distance from the steering axis to the center of the wheels [m]
wheel_lever_arm: 0.045

# velocity below which the steering for a wheel is disabled [m/s]
#   it is used to avoid unnecessary steering movement
zero_vel_threshold: 0.001

# velocity below which it is allowed to move a wheel into the outward position [m/s]
small_vel_threshold: 0.02

# hysteresis parameter for deciding when to move a wheel to the outward position [deg]
#   0 deg = as soon as possible (which is unstable)
#   >= 90 deg will disable the feature
steer_hysteresis: 30

# hysteresis parameter for deciding in which way to turn a wheel in case of ambiguity [deg]
#   0 deg is unstable
#   lower is better (in theory)
steer_hysteresis_dynamic: 5

# proportional gain for steering angle controller [1/s]
steer_gain: 10

# how far to predict steering angle into the future for steering angle controller [s]
#   higher values lead to slower movement and avoid over-shooting
steer_lookahead: 0.06

# smoothing filter gain for steering angle control [1]
#   used to decrese gear noise and wear
#   low values will increase the smoothing
#   1 = no filtering
steer_low_pass: 0.5

# maximum velocity for steering [rad/s]
max_steer_vel: 8.0

# smoothing filter gain for drive velocity [1]
#   used to decrese gear noise and wear
#   low values will increase the smoothing
#   1 = no filtering
drive_low_pass: 0.5

# timestamp adjustment for joint_states message [s]
motor_delay: 0.0

# if to publish odometry on tf
broadcast_tf: true

# if to home automatically at startup
auto_home: true

# joystick button index for manual homeing (-1 to disable)
homeing_button: 0

# joystick button index for steering reset (-1 to disable)
steer_reset_button: 1

# if to measure drive motor torques
#   values are published as 'effort' in [Nm] in joint_states message
measure_torque: false

# socketcan interface name for motor CAN bus
can_iface: can0

# optional group id for motors (-1 disables the feature)
#   usued to lower CAN bus load
motor_group_id: 30

# timeout value for /cmd_vel topic [s]
#   upon timeout the platform will stop
#   when sending commands over wifi a timeout of >= 1 second is needed
cmd_timeout: 1.0

# timeout value for /drives/joint_trajectory message [s]
#   upon timeout the platform will stop
trajectory_timeout: 0.2

# timeout value for motor responses to status update requests [s]
#   upon timeout all motors will be stopped
motor_timeout: 0.5

# homing velocity [rad/s]
home_vel: -1.0

