# ---- motor parameters ----
# 
# for each drive module a set of drive and steer parameters follow:
#   driveX:
#     can_id: CAN bus "ID" as defined in the motor controller ROM
#     joint_name: ROS joint name for this motor
#     rot_sign: rotation direction (1 or -1)
#     gear_ratio: gear ratio of the gearbox and/or belt drive
#     enc_ticks_per_rev: number of encoder ticks per motor revolution [1]
#     torque_constant: constant to convert from motor current [A] to motor torque in [Nm]
#   steerX:
#     <same parameters as drive motor plus more>
#     center_pos_x: X position of the steering axis [m]
#     center_pos_y: Y position of the steering axis [m]
#     home_angle: home angle of the drive module [deg]
#     home_dig_in: digital input pin for the homing switch
#     enc_home_offset: encoder offset to correct home position [ticks]

# ---- front left ----
drive0:
  can_id: 2
  joint_name: wheel_0_joint
  rot_sign: -1
  gear_ratio: 30
  enc_ticks_per_rev: 10000
  torque_constant: 0.116
steer0:
  can_id: 1
  joint_name: mpo_700_head_0_joint
  center_pos_x: 0.240
  center_pos_y: 0.190
  rot_sign: 1
  gear_ratio: 19
  enc_ticks_per_rev: 10000
  torque_constant: 0.116
  home_angle: 180.0
  home_dig_in: 9
  enc_home_offset: 4663

# ---- back left ----
drive1:
  can_id: 4
  joint_name: wheel_1_joint
  rot_sign: 1
  gear_ratio: 30
  enc_ticks_per_rev: 10000
  torque_constant: 0.116
steer1:
  can_id: 3
  joint_name: mpo_700_head_1_joint
  center_pos_x: -0.240
  center_pos_y: 0.190
  rot_sign: -1
  gear_ratio: 19
  enc_ticks_per_rev: 10000
  torque_constant: 0.116
  home_angle: 180.0
  home_dig_in: 9
  enc_home_offset: -5429

# ---- back right ----
drive2:
  can_id: 6
  joint_name: wheel_2_joint
  rot_sign: -1
  gear_ratio: 30
  enc_ticks_per_rev: 10000
  torque_constant: 0.116
steer2:
  can_id: 5
  joint_name: mpo_700_head_2_joint
  center_pos_x: -0.240
  center_pos_y: -0.190
  rot_sign: 1
  gear_ratio: 19
  enc_ticks_per_rev: 10000
  torque_constant: 0.116
  home_angle: 0.0
  home_dig_in: 9
  enc_home_offset: 4845

# ---- front right ----
drive3:
  can_id: 8
  joint_name: wheel_3_joint
  rot_sign: 1
  gear_ratio: 30
  enc_ticks_per_rev: 10000
  torque_constant: 0.116
steer3:
  can_id: 7
  joint_name: mpo_700_head_3_joint
  center_pos_x: 0.240
  center_pos_y: -0.190
  rot_sign: -1
  gear_ratio: 19
  enc_ticks_per_rev: 10000
  torque_constant: 0.116
  home_angle: 0.0
  home_dig_in: 9
  enc_home_offset: -5363

